---
- name: configure apache2
  hosts: all
  tasks: 
   - name: install apache2
     apt: 
      name: apache2
      state: present
      update_cache: yes
   - name: Edit the index.html file
     copy:
       content: "welcome to Hyderabad"
       dest: /var/www/html/index.html
   - name: restart apache2
     service:
        name: apache2
        state: restarted
   - name: check apache2 responce in all the servers
     uri:
       url: "{{item}}"
       status_code: 200
     with_items:
       - http://172.31.29.245
       - http://172.31.30.39
...
