---
- name: create users and create files/dir in user home dir with variables examples
  hosts: all
  tasks: 
   - name: create user
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
   - name: create file/dir
     file: 
      name: "{{d}}"
      state: "{{e}}"
...        


