---
- name: Install firewall software by using hosts
  hosts: webserver
  tasks: 
   - name: install firewall in webservers
     apt: 
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...
