---
- name: create user and copy files into the same user home directory
  hosts: all
  tasks:
    - name: creat user 
      user:                         
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: ravi,b: 223,c: /tmp/ravi}
        - {a: rani,b: 445,c: /home/rani}
    - name: copy files in user home directory
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /tmp/ravi}
        - {a: /etc/group,b: /home/rani}
...          
            
